version: "{build}"

environment:
    global:
        HAXELIB_ROOT: C:\projects\haxelib

install:
    - cinst haxe -y
    - RefreshEnv
    - mkdir "%HAXELIB_ROOT%"
    - haxelib setup "%HAXELIB_ROOT%"
    - haxelib install hxcpp 3.1.39 > log.txt || type log.txt
    - haxelib list

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%\project
    - haxelib run hxcpp build.xml
    - cd %APPVEYOR_BUILD_FOLDER%
    - haxelib dev hxSerial .
    - haxe compile.hxml

test_script:
    - copy /y ndll\Windows\* bin
    - cd %APPVEYOR_BUILD_FOLDER%\bin
    - Test.exe
    - neko Test.n
